name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README.md for project
        uses: neutrinomuon/UpdateREADME@v0.0.3
